---

- name: packages update list
  apt: >
    update_cache=yes
    cache_valid_time=180
  sudo: yes

- name: packages
  apt: name={{ item }} state=latest
  with_items:
    - build-essential
    - wget
    - unzip
    - rsync
    - curl